---
- name: add port in firewall 
  shell: "{{ item }}"
  with_items:
  - firewall-cmd --add-service=nfs --permanent
  - firewall-cmd --add-port=2049/udp --permanent
  - firewall-cmd --add-port=2049/tcp --permanent
  - firewall-cmd --add-port=111/tcp --permanent
  - firewall-cmd --add-port=111/udp --permanent
  - firewall-cmd --add-port=20048/udp --permanent
  - firewall-cmd --add-port=20048/tcp --permanent
  - 'firewalld-cmd --reload'
